pluginId=pano-plugin-link-redirect
pluginName=Link Redirect
pluginDescription=Create simple or advanced URL redirects with delay, custom pages, and menu integration. 
pluginPanoVersion=local-build
pluginClass=com.panomc.plugins.linkredirect.LinkRedirectPlugin
pluginDeveloper=Pano
pluginLicense=MIT
pluginSourceUrl=https://github.com/panomc/pano-plugin-link-redirect
pluginDependencies=
pluginRequires=

pf4jVersion=3.11.1
vertxVersion=4.5.7
gsonVersion=2.11.0
handlebarsVersion=4.4.0
springContextVersion=5.3.39
organization=panomc